name: Signature-verification

on:
  push:
    branches:
      - master
    paths:
      - 'signature-verification/**'

  pull_request:
    paths:
      - 'signature-verification/**'
      - .github/workflows/signature-verification.yml

  workflow_dispatch: {}

defaults:
  run:
    working-directory: ./signature-verification

permissions:
  id-token: write
  contents: read

jobs:
  signature-verification:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 10.28.2
      - uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'
          check-latest: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm check:oxlint
      - run: pnpm check:type
      - run: pnpm check:format
      - run: pnpm check:knip
      - run: pnpm test
      - name: Publish
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        uses: botpress/gh-actions/publish-if-not-exists@master
        with:
          path: './signature-verification'
